### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by miguelavaqrod** [davidjamesstone/noide#9]
Hi,

Trying to find why running noide always binds to all interfaces instead of localhost, I found a small typo in one file.

In server/manifest.js:
...
host: config.server.home,
...

Instead of "home"... I think it is "host", so it binds fine.

Regards.

**Comment by davidjamesstone** [comment]
Good spot! Thankyou!

**Comment by miguelavaqrod** [comment]
Your welcome
Thanks to that great piece of software!!
